-- Upgrade the form-schema JSON of two TTS providers.
--   SYSTEM_TTS_MinimaxStreamTTS: model becomes a static select of Minimax speech
--   models, voice_id becomes a select backed by the dynamic voices list.
--   SYSTEM_TTS_openai: voice becomes a static select of the six OpenAI voices.
-- All other field entries are preserved verbatim from the state seeded by
-- 202509051745 / 202504082211 and relabelled by 202609251530 / 202609251600.

UPDATE `ai_model_provider` SET `fields` = '[{"key":"group_id","label":"Group ID","type":"string"},{"key":"api_key","label":"API Key","type":"string"},{"key":"model","type":"select","label":"Model","options":[{"value":"speech-2.8-hd","label":"speech-2.8-hd (best quality)"},{"value":"speech-2.8-turbo","label":"speech-2.8-turbo (fast)"},{"value":"speech-2.6-hd","label":"speech-2.6-hd"},{"value":"speech-2.6-turbo","label":"speech-2.6-turbo"},{"value":"speech-02-hd","label":"speech-02-hd"},{"value":"speech-02-turbo","label":"speech-02-turbo"},{"value":"speech-01-hd","label":"speech-01-hd"},{"value":"speech-01-turbo","label":"speech-01-turbo"}]},{"key":"voice_id","type":"select","label":"Voice ID","dynamic":"voices"},{"key":"output_dir","label":"Output Directory","type":"string"},{"key":"voice_setting","label":"Voice Settings","type":"dict","dict_name":"voice_setting"},{"key":"pronunciation_dict","label":"Pronunciation Dictionary","type":"dict","dict_name":"pronunciation_dict"},{"key":"audio_setting","label":"Audio Settings","type":"dict","dict_name":"audio_setting"},{"key":"timber_weights","label":"Voice Weights","type":"string"}]' WHERE `id` = 'SYSTEM_TTS_MinimaxStreamTTS';

UPDATE `ai_model_provider` SET `fields` = '[{"key":"api_key","label":"API Key","type":"string"},{"key":"api_url","label":"API URL","type":"string"},{"key":"model","label":"Model","type":"string"},{"key":"voice","type":"select","label":"Voice","options":[{"value":"alloy","label":"alloy"},{"value":"echo","label":"echo"},{"value":"fable","label":"fable"},{"value":"onyx","label":"onyx"},{"value":"nova","label":"nova"},{"value":"shimmer","label":"shimmer"}]},{"key":"speed","label":"Speed","type":"number"},{"key":"output_dir","label":"Output Directory","type":"string"}]' WHERE `id` = 'SYSTEM_TTS_openai';
